language: scala
scala:
- 2.11.12
- 2.12.4
jdk:
- oraclejdk8
- oraclejdk9
env:
  matrix:
  - SCRIPT=scripts/test-sbt
  - SCRIPT=scripts/test-gradle
script:
- "$SCRIPT"
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.gradle/caches"
before_cache:
- rm -rf $HOME/.ivy2/cache/com.typesafe.play/*
- rm -rf $HOME/.ivy2/cache/scala_*/sbt_*/com.typesafe.play/*
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -print0 | xargs -n10 -0 rm
matrix:
  exclude:
  - scala: 2.11.12
    jdk: oraclejdk9
addons:
  ssh_known_hosts: 52.165.158.46
before_deploy:
- sbt dist
- openssl aes-256-cbc -K $encrypted_5cacd6c3533d_key -iv $encrypted_5cacd6c3533d_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/target/universal  bernardoherrera@52.165.158.46:/home/bernardoherrera
  on:
    branch: 2.6.x